### ISSUE TITLE
Port code to PyMC3

### ISSUE THREAD

**Issue by twiecki** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#155]
PyMC3 is coming along quite nicely and is a major improvement upon pymc 2. I thus think a port of PPfH to PyMC3 would be very useful, especially since pymc3 is not well documented yet. All examples should be easy to port.

I don't think such a PR should be merged into master as pymc 2 is probably still around to stay and much more stable. But having a forked book would be quite nice. Certainly this point is up for debate.

**Comment by hadim** [comment]
Any news here ?

**Comment by twiecki** [comment]
@hadim Interested in leading the charge here?

**Comment by hadim** [comment]
Well I already did it for chapter 1 but I just see that it is already done in https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/tree/pymc3.

I am sorry but for the others chapters I don't have neither the time and the knowledge to do it in a short term.

Maybe you could add a "call for contributor" on the README of the `master` branch about the porting to `pymc3`. You could also open a PR against `pymc3` to track progress.

**Comment by hadim** [comment]
Please see #268.

(this issue can be closed)
