### ISSUE TITLE
Question on chapter 1 exercise 2

### ISSUE THREAD

**Issue by alexandrekow** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#246]
I tried to do the exercises in chapter 1 but I am not sure of my solution. 
1. What is the expected percentage increase in text-message rates? hint: compute the mean of lambda_1_samples/lambda_2_samples. **Note that this quantity is very different from** lambda_1_samples.mean()/lambda_2_samples.mean().

When I do 

``` python
print (lambda_1_samples/lambda_2_samples).mean(), lambda_1_samples.mean()/(lambda_2_samples.mean()
```

I find: 

> 0.783421896592 0.782213782031

and they don't look very different to me. 

Am I doing something wrong? 
Is there a page with the solutions?

**Comment by nanounanue** [comment]
I have the same questions...

**Comment by CamDavidsonPilon** [comment]
Hehe I guess this is just a bad problem, and it turns out they are almost they same! I'll confirm later

**Comment by nanounanue** [comment]
Ok, thanks :)
