### ISSUE TITLE
suggestion: Shoud we build the PDF and put it on the github for downloading?

### ISSUE THREAD

**Issue by andyyuan78** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#262]
thanks!

**Comment by CamDavidsonPilon** [comment]
Yes, that would be nice!

**Comment by andyyuan78** [comment]
So, would you like do it ? you konw, I am blocked since I canonot generate the PDF.
thanks

**Comment by andyyuan78** [comment]
anyone can help on it?

**Comment by waanng** [comment]
I can help generate PDF file, but the article is changing on time, can you sent me which part is ok for PDF? @CamDavidsonPilon

**Comment by andyyuan78** [comment]
thanks Waanng, I guess all parts may be changed in the future, so just put pdfs in a folder and have a regular update.

**Comment by waanng** [comment]
ok, I will convert all the *.ipynb file into pdf with a regular update

**Comment by andyyuan78** [comment]
To waanng: great! thanks!
