### ISSUE TITLE
Use of term 'Expected Value' very sudden in Chapter 1

### ISSUE THREAD

**Issue by mayankasthana** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#265]
In the first chapter, under Probability Distributions, Discrete Case, the discussion on expected value is very sudden.

    One useful property of the Poisson distribution is that its expected value is equal to its parameter, i.e.:
    E[Z|λ]=λ

I have no idea what expected value means. Is E the same as P? The term `E[Z|λ]` looked very similar to `P(A|X)` which was the `posterior probability` discussed above. But in this case `λ` is not an event as `X` was! This left me confused. 

Maybe a quick explanation of what **Expected Value** means before using it would be very helpful.

**Comment by CamDavidsonPilon** [comment]
:+1: :+1: good idea, thanks for bringing this up

**Comment by pieteradejong** [comment]
@CamDavidsonPilon is this still open? if so, would be happy to take on

**Comment by pieteradejong** [comment]
@CamDavidsonPilon Follow-up: took a stab at this, added to PR #291

**Comment by mayankasthana** [comment]
Thanks @pieteradejong
