### ISSUE TITLE
Chapter 6: Mean-Variance Optimisation Loss Function

### ISSUE THREAD

**Issue by Anjum48** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#277]
Hi Cam,

Could you explain how to use (or reference to a source) this loss function:

![screenshot from 2015-09-18 12 24 13](https://cloud.githubusercontent.com/assets/13783303/9958358/dbb0269e-5e00-11e5-8c78-7d86dbe4e0e7.png)

I'm assuming that the loss function is attempting to minimise the portfolio weights for the 4 stocks (which can be done using scipy optimise etc.), but I'm not sure what the lambda parameter is.

Thanks!

**Comment by pieteradejong** [comment]
@Anjum48 which chapter is this?
@CamDavidsonPilon lambda seems like the regularization parameter?

**Comment by CamDavidsonPilon** [comment]
>  loss function is attempting to minimise the portfolio weights for the 4 stocks

This is trivially solved by setting them all to negative infinity, so I don't think you meant to say that. It's two counteracting forces: the larger the weights, the larger the first term (return), but also the larger the variance (second term). 

The lambda parameter is a user specified parameter that is a tradeoff between maximizing the return (the first term) and the second term (the portfolio variance). It's not a regularizer in the traditional regression sense but it is analogous. 

This is a pretty common formula in finance - it's the lagrangian of a quadratic problem: http://www.actuaries.org/AFIR/Colloquia/Rome2/Cesarone_Scozzari_Tardella.pdf

**Comment by yiyuezhuo** [comment]
@CamDavidsonPilon
I don't understand that the optimizer use `min`, I mean, you should want to maximize your return and 
be penalized by variance. So you should use `max` or append a negative sign instead of using `min`.

**Comment by mdengler** [comment]
The lambda 𝛌 is often referred to ([e.g. here](https://web.stanford.edu/group/SOL/dissertations/HowardShek_Stanford_PhDThesis_electronicsubmission-augmented.pdf)) as the "risk aversion" parameter -- the tradeoff @CamDavidsonPilon mentions.

**Comment by rsvp** [comment]
If $\lambda$ is 1, then the objective function approximates the portfolio's
*geometric* mean return, and that's something one should ***maximize***
with respect to the weights.

**Comment by mdengler** [comment]
There definitely seems to be a minus sign missing.

**Comment by CamDavidsonPilon** [comment]
Yea it should be `max` 👍

**Comment by rsvp** [comment]
OK, fix done: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/347 for two notebooks.
