### ISSUE TITLE
Version 3 Notebooks

### ISSUE THREAD

**Issue by brennon** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#284]
I'd love to contribute a number of changes/additions. However, all notebooks are currently in version 3 format. IPython automatically converts old formats to the current format, and a `git diff` of this shows that the changes this makes are fairly substantial. I'm not sure you want us submitting pull requests with the notebook versions upgraded (though this might be a good idea). Furthermore, I can't seem to find an option to open a notebook in the existing version and *not* convert it (or to save it in the old version). What would you like us to do?

**Comment by CamDavidsonPilon** [comment]
yeeee I've been meaning to do this for a while, I'll make it happen soon!

**Comment by brennon** [comment]
Are you open to someone just going through the existing notebooks, saving into version 4 format, and submitting a pull request? I'm happy to do it.

**Comment by CamDavidsonPilon** [comment]
Yes I would be, :+1:
