### ISSUE TITLE
Print vs Online?

### ISSUE THREAD

**Issue by stmax82** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#303]
Hi,

could you please explain what the state of the online version of this book is compared to the print version? Which one is more up to date?

I read this book online a while ago and decided to buy the print version when it came out in October (because I really liked it and wanted to acknowledge the work you put into writing it - thanks).

While browsing through the printed book I notice small differences to the online version - while the print version seems to contain improvements/fixes that are missing in the online version.

One example being in chapter 1 exercise 2:

The online version recommends to calculate the **expected percentage increase** with

"**mean of lambda_1_samples/lambda_2_samples**"

while the print version recommends to calculate it with

"**mean of (lambda_2_samples - lambda_1_samples) / lambda_1_samples**" (which makes much more sense)

Also answers to the exercises are available in the print version, but not in the online version.

**Comment by CamDavidsonPilon** [comment]
Hey there, I've added some differences to the README: https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#printed-version-by-addison-wesley
