### ISSUE TITLE
Chapter 3: KeyError: 'stds'  (In [10]:)

### ISSUE THREAD

**Issue by usptact** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#308]
Running the block In [10] results in a KeyError, it looks like there is no variable "stds" found in the model. This is strange as the variable "taus" has been defined in block In [7] and included later in the model.

In the book, this is the section 3.1.4: Example: Unsuprvised Clustering Using Mixture Model

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-1dbea2bd1113> in <module>()
     14 
     15 plt.subplot(312)
---> 16 std_trace = mcmc.trace("stds")[:]
     17 plt.plot(std_trace[:, 0], label="trace of standard deviation of cluster 0",
     18      c=colors[0], lw=lw)

/usr/local/lib/python2.7/dist-packages/pymc/Model.pyc in trace(self, name, chain)
    832         """
    833         if isinstance(name, str):
--> 834             return self.db.trace(name, chain)
    835         elif isinstance(name, Variable):
    836             return self.db.trace(name.__name__, chain)

/usr/local/lib/python2.7/dist-packages/pymc/database/base.pyc in trace(self, name, chain)
    371           the ith call to `sample`.
    372         """
--> 373         trace = copy.copy(self._traces[name])
    374         trace._chain = chain
    375         return trace

KeyError: 'stds'
```

**Comment by usptact** [comment]
I managed to circumvent the problem by defining "sigmas":
sigmas = pm.Uniform("stds",0,100,size=2)

and then creating a deterministic variable "taus":
@pm.deterministic
def taus(sigmas=sigmas):
   return 1.0 / sigmas **2

When building the model, I only had to add the "sigmas" variable to the list and then do inference. The examples worked after this hack.

**Comment by CamDavidsonPilon** [comment]
Hm, cool, I'll look into this. Thanks for reporting it!

**Comment by CamDavidsonPilon** [comment]
@usptact is the same solution I found, and the correction going into the erratum 👍
