### ISSUE TITLE
Typo in Section 1.6.2 of ebook version

### ISSUE THREAD

**Issue by kwkelly** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#314]
The model specifies tau_1 twice, but the second one should be tau_2. Just a minor error.

Screen shot [here.](http://i.imgur.com/o3V1qEr.png)

I searched and didn't see this reported, but I also don't see it in the python notebooks.

**Comment by CamDavidsonPilon** [comment]
oh nice, that's correct - would you like to submit a PR to fix it?

**Comment by kwkelly** [comment]
I don't see any code for the ebook (epub) version that I could clone and edit?

**Comment by CamDavidsonPilon** [comment]
whoops, I got confused. Roger, I'll add this to the errata.

**Comment by kwkelly** [comment]
Sounds good, this can be closed then I think.
