### ISSUE TITLE
Broken link to chapters from the first page

### ISSUE THREAD

**Issue by metakermit** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#323]
When browsing [your book's introduction](http://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Prologue/Prologue.ipynb), the links to chapters are broken – e.g. [chapter 1](http://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Chapter1.ipynb).

The same thing happens when I try to open your book from the [nbviewer home page](http://nbviewer.jupyter.org/).

**Comment by CamDavidsonPilon** [comment]
Ah, the prolouge's link were forgotten, thanks. 

I've pinged the nbviewer team to update the homepage, thanks!

**Comment by twiecki** [comment]
These also need updating: http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/#contents

CC @mmargenot

**Comment by CamDavidsonPilon** [comment]
Updated these links (nbviewer homepage is still broken though, I've pinged them)
