### ISSUE TITLE
Links on homepage still broken

### ISSUE THREAD

**Issue by twiecki** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#326]
Under contents: http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/#prologue the links go to a 404, e.g:
http://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb

**Comment by CamDavidsonPilon** [comment]
👍 nice catch, fixed now
