### ISSUE TITLE
Freshman needs help! How can I build up the environment? 

### ISSUE THREAD

**Issue by MigicMice** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#348]
Hi,man.I'm a Chinese reader of your book.It's pretty good,but it's not that friendly to freshman.
I have trouble for the very first example.I've installed the anaconda to install the pymc,(btw I'm using 
pycharm on macos).Does the project must be run on jupyter? I just copy the code in the book and run it in pycharm,but it doesn't work. Here is the error"AttributeError: Unknown property colors".
OMG,just give the poor freshman some help,PLEASE.

**Comment by syzer** [comment]
Isn't that question more about how to use python, and not this book?

**Comment by jaymzcd** [comment]
These are python notebooks - you won't be able to just paste it into Pycharm and get it to work automatically (Pycharm for what it's worth _does_ support running jupyter notebooks if you [follow the steps](https://www.jetbrains.com/help/pycharm/using-ipython-jupyter-notebook-with-pycharm.html)).

Instead, you are probably best off just: 

1. Open the Terminal app
1. Change directory (`cd`) to the folder where you have downloaded the entire project
1. Run `jupyter notebook`
1. Open your browser to the link it will have printed in the terminal
1. Navigate to the relevant notebook you want to run

If none of that makes much sense I would recommend working through the [beginners guides](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html) to _jupyter_ first. There are a lot of resources and guides to this, eg. this [youtube video](https://www.youtube.com/watch?v=HW29067qVWk) if you prefer to follow along.

**Comment by MigicMice** [comment]
@jaymzcd Thank you for your patient reply.

**Comment by CamDavidsonPilon** [comment]
Thanks @jaymzcd!
