### ISSUE TITLE
Why do we automatically (arbitrarily?) choose an exponential distribution?

### ISSUE THREAD

**Issue by vegabook** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#351]
I've bought the book, and I love it, but I'm just wondering, in Chapter 1, why an exponential distribution is chosen with the somewhat arbitrary reasoning that "As we saw earlier, the exponential distribution provides a continuous density function for positive numbers, so it might be a good choice for modeling λi".

Why not a uniform distribution? Why not some other distribution? Why this one?

**Comment by CamDavidsonPilon** [comment]
It's part of the modellers choice (a degree of freedom). I chose exponential for a few reasons:

1) I suspected the unknowns to be near 20-30, but I didn't want to force them into that range (which would happen if I used a Uniform)
2) Allows for tapering: 30 is possible, 31 less so, 32 less than that, and so on. This reflects my intuition. (However a consequence of this means that I suspect it is 0 with the _most_ chance)
3) Good introduction to non-trivial priors, and connects back the material just learned.

You're right though, I could have used Uniforms, and this is something that can be tested as well. If we derive the same or similar inference, that just gives more evidence that the original inference is robust.
