### ISSUE TITLE
Chapter 4 Notebook - NotJSONError

### ISSUE THREAD

**Issue by Tomesco** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#376]
Opening the chapter 4 notebook (both Python2 and 3) in Jupyter returns 
`NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...',)`

**Comment by Tomesco** [comment]
I believe this is addressed in pull request #375.

**Comment by CamDavidsonPilon** [comment]
Fixed in master, thanks @Tomesco!
