### ISSUE TITLE
Capter 5 module 'pymc3.variational' has no attribute 'advi'

### ISSUE THREAD

**Issue by yuliang0225** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#385]
In[8]
with model:
    mu, sds, elbo = pm.variational.advi(n=50000)
    step = pm.NUTS(scaling=model.dict_to_array(sds), is_cov=True)
    trace = pm.sample(5000, step=step, start=mu)
Out
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-cba5e8e72e58> in <module>()
      3 
      4 with model:
----> 5     mu, sds, elbo = pm.variational.advi(n=50000)
      6     step = pm.NUTS(scaling=model.dict_to_array(sds), is_cov=True)
      7     trace = pm.sample(5000, step=step, start=mu)

AttributeError: module 'pymc3.variational' has no attribute 'advi'

------------------------------
pymc3:           3.4.1-py36_0

**Comment by yuliang0225** [comment]
I had updated my PyMC to 3.4.1.

**Comment by yuliang0225** [comment]
I understand where is wrong.  The code should be updated.

**Comment by edoven** [comment]
@yuliang0225 how did you solve? I'm having the same problem.

**Comment by ryanxiang0306** [comment]
how to updated the code ?

**Comment by BartKeulen** [comment]
I cannot find the updated code either.

@yuliang0225 please add your fix.

**Comment by bernha18** [comment]
same issue, somebody figured out?

**Comment by ysgit** [comment]
anyone who gets here and is trying to solve it, replace the code block with:
```python
with model:
    trace = pm.sample(5000, advi_map=True)
```

**Comment by JohnPaton** [comment]
+1
