### ISSUE TITLE
Ch2&Ch3 - I got every trace with the number of several times draws

### ISSUE THREAD

**Issue by EmpRamses** [CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers#419]
In chapter 3,  the last cell warns me that "ValueError: x and y must have same first dimension, but have shapes (50000,) and (275000,)"

In the book, the first dim. of. every trace is equal to the num. of draws as pictures showed bellow.
<img width="1058" alt="2018-11-15 10 00 33" src="https://user-images.githubusercontent.com/10172561/48524994-6540ab00-e8bd-11e8-9f0a-b54098c72aaa.png">
<img width="690" alt="2018-11-15 10 00 49" src="https://user-images.githubusercontent.com/10172561/48524995-65d94180-e8bd-11e8-9ce3-506d36ee6339.png">
However, in my experiment with codes in the book, I got trace with much more 1st dim.
For instance, in. chapter 3, when I want to sample 4 vars for 25000 draws, I got traces with 100000(4 * draws) as 1st dim.
![ch3](https://user-images.githubusercontent.com/10172561/48525440-20b60f00-e8bf-11e8-8b83-2d29e8587be8.jpg)

**Comment by star-yar** [comment]
Found related discussion https://github.com/pymc-devs/pymc3/pull/2743 .
